// Code generated by a test. DO NOT EDIT.

package linedirective

import "log"

// A generated file is not reported, below a //line directive too.
//
//line gen.tmpl:1
func generated() error {
	err := do()
	log.Println(err)
	return err
}
