package main_test

import (
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strings"
	"testing"
)

// buildBinary builds the command as a user installs it.
func buildBinary(t *testing.T) string {
	t.Helper()
	bin := filepath.Join(t.TempDir(), "errlogreturn")
	out, err := exec.Command("go", "build", "-o", bin, ".").CombinedOutput()
	if err != nil {
		t.Fatalf("go build: %v\n%s", err, out)
	}
	return bin
}

// run writes a module holding files into a fresh directory, runs the command
// over it, and returns the output lines with the directory trimmed, sorted,
// and the exit code.
func run(t *testing.T, bin string, files map[string]string) ([]string, int) {
	t.Helper()
	dir := t.TempDir()
	files["go.mod"] = "module example.com/e2e\n\ngo 1.27\n"
	for name, src := range files {
		path := filepath.Join(dir, name)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(src), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	cmd := exec.Command(bin, "./...")
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	code := 0
	if exit := (*exec.ExitError)(nil); errors.As(err, &exit) {
		code = exit.ExitCode()
	} else if err != nil {
		t.Fatalf("run: %v\n%s", err, out)
	}
	// The go command may resolve the directory through a symlink.
	real, err := filepath.EvalSymlinks(dir)
	if err != nil {
		t.Fatal(err)
	}
	text := strings.ReplaceAll(string(out), real+string(filepath.Separator), "")
	text = strings.ReplaceAll(text, dir+string(filepath.Separator), "")
	var lines []string
	for l := range strings.Lines(text) {
		if l = strings.TrimRight(l, "\n"); l != "" {
			lines = append(lines, l)
		}
	}
	slices.Sort(lines)
	return lines, code
}

// logged is a function that logs its error and returns it. The header goes
// above it, so a //line directive can sit between the imports and the code.
func logged(pkg, header, body string) string {
	return "package " + pkg + `

import (
	"errors"
	"log/slog"
)

` + header + `func Run() error {
	err := errors.New("x")
	if err != nil {
` + body + `		return err
	}
	return nil
}
`
}

const logLine = "\t\tslog.Error(\"failed\", \"err\", err)\n"

// TestLineDirective runs the command over a //line directive, which renames
// every position below it. It changes where a report is printed, and nothing
// else: what is reported and what an ignore silences stay the same.
func TestLineDirective(t *testing.T) {
	bin := buildBinary(t)
	tests := []struct {
		name  string
		files map[string]string
		want  []string
		code  int
	}{
		{
			name:  "control without //line",
			files: map[string]string{"a/a.go": logged("a", "", logLine)},
			want: []string{
				"a/a.go:11:3: error is logged here and also returned at line 12; log it or return it, not both",
				"a/a.go:12:3: \treturned here",
			},
			code: 3,
		},
		{
			name:  "report below //line",
			files: map[string]string{"b/b.go": logged("b", "//line run.tmpl:1\n", logLine)},
			want: []string{
				"b/run.tmpl:4: error is logged here and also returned at line 5; log it or return it, not both",
				"b/run.tmpl:5: \treturned here",
			},
			code: 3,
		},
		{
			name:  "ignore below //line",
			files: map[string]string{"c/c.go": logged("c", "//line run.tmpl:1\n", "\t\t//errlogreturn:ignore\n"+logLine)},
			code:  0,
		},
		{
			name: "generated file with //line",
			files: map[string]string{"d/d.go": "// Code generated by a test. DO NOT EDIT.\n\n" +
				logged("d", "//line run.tmpl:1\n", logLine)},
			code: 0,
		},
		{
			name: "lines one number apart across two //line regions",
			files: map[string]string{"e/e.go": `package e

import (
	"errors"
	"log/slog"
)

//line a.tmpl:10
func First() error {
	err := errors.New("x")
	//errlogreturn:ignore
	slog.Error("failed", "err", err)
	return err
}

//line b.tmpl:11
func Second() error {
	err := errors.New("x")
	slog.Error("failed", "err", err)
	return err
}
`},
			want: []string{
				"e/b.tmpl:13: error is logged here and also returned at line 14; log it or return it, not both",
				"e/b.tmpl:14: \treturned here",
			},
			code: 3,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, code := run(t, bin, tt.files)
			if code != tt.code || !slices.Equal(got, tt.want) {
				t.Errorf("exit %d, output:\n%s\nwant exit %d, output:\n%s",
					code, strings.Join(got, "\n"), tt.code, strings.Join(tt.want, "\n"))
			}
		})
	}
}
